### ISSUE TITLE
Clickable charts

### ISSUE THREAD

**Issue by timoline** [PaulCornelissen/YoulessMonitor#3]
Volgens mij is dit nog niet toegevoegd
http://gathering.tweakers.net/forum/list_message/44328821#44328821

**Comment by PaulCornelissen** [comment]
Ik heb die code gebruikt om vergelijkbare functionaliteit te implementeren. Het werkt nu vanuit het maand- en jaaroverzicht. Vanuit het live-, dag- en weekoverzicht is het imho niet logisch om door te klikken naar een dagoverzicht, dus daarvoor is het niet gemaakt.
